[programs.localnet]
p0001 = "ArVfLdaEaEQqEevZeLQSct21udmEkB9wij9tf86Wtth4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/metalgear/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
